// Created by Crowbar 0.68

// Stored modelname (without quotes): "F:\Halflife originals\models\shotgunshell\w_shotshell.mdl"
$modelname "w_shotshell.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "shell"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "shell01" -5.57 -1.79 0 5.58 7.74 7.77

$sequence "idle" {
	"w_shotshell_anims\idle"
	fps 30
}
