// Created by Crowbar 0.68

// Stored modelname (without quotes): "C:\Program Files\ICQ\Received Files\BB\w_weaponbox.mdl"
$modelname "w_weaponbox.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "wrld_itemcontainer"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Backpack1" -8 -8 -8 8 8 8

$sequence "idle" {
	"w_weaponbox_anims\idle"
	fps 30
}
