// Created by Crowbar 0.68

// Stored modelname (without quotes): "C:\MilkShape 3D\Wanted\Crispen\med_bottle.mdl"
$modelname "medicine.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "body"
{
	studio "medicine_bottle"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "joint1" -8 -8 -8 8 8 8

$sequence "idle1" {
	"medicine_anims\idle1"
	fps 30
}
