// Created by Crowbar 0.68

// Stored modelname (without quotes): "F:\wanted\bags\w_bag2.mdl"
$modelname "w_bag2.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "bag2"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "joint1" -12.93 -0.06 -13.01 18.27 54.580002 15.71

$sequence "idle" {
	"w_bag2_anims\idle"
	fps 30
}
