// Created by Crowbar 0.68

// Stored modelname (without quotes): "F:\Halflife originals\models\shotgunbox\w_shotbox.mdl"
$modelname "w_shotbox.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "box"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "SHELL01" -10.69 -8.69 -5.16 7.19 9.29 12.98

$sequence "idle" {
	"w_shotbox_anims\idle"
	fps 30
}
