// Created by Crowbar 0.68

// Stored modelname (without quotes): "F:\wanted\bags\w_bag1.mdl"
$modelname "w_bag1.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "bag1"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "joint1" -14.18 -0.15 -12.06 15.39 43.93 14.05

$sequence "idle" {
	"w_bag1_anims\idle"
	fps 30
}
