// Created by Crowbar 0.68

// Stored modelname (without quotes): "valve/models/concretegibs.mdl"
$modelname "concretegibs.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "parts"
{
	studio "chunk1_big"
	studio "chunk1_biggest"
	studio "chunk1_small"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "" -4.06 -3.65 -5.72 6.76 2.72 5.72

$sequence "idle1" {
	"concretegibs_anims\idle1"
	fps 30
}
