// Created by Crowbar 0.68

// Stored modelname (without quotes): "D:\sierra\half-life\valve\models\w_crowbar.mdl"
$modelname "w_pick.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "w_pick"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Frame 1" -1.8 0 -8.81 1.91 27.26 13.7

$sequence "idle" {
	"w_pick_anims\idle"
	fps 30
}
