// Created by Crowbar 0.68

// Stored modelname (without quotes): "C:\MilkShape 3D\Wanted\Steer Skull\steerskull.mdl"
$modelname "steerskull.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "body"
{
	studio "steerskull"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "joint1" -13.97 -5.73 -11.41 13.97 9.87 22.370001

$sequence "idle1" {
	"steerskull_anims\idle1"
	fps 30
}
