// Created by Crowbar 0.68

// Stored modelname (without quotes): "F:\wanted\cannon\w\w_cannon.mdl"
$modelname "w_cannon.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "body"
{
	studio "newrpg_worldmodel"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Cylinder01" -10.13 -10.18 -30.82 11.48 11.98 31.9

$sequence "stayput" {
	"w_cannon_anims\stayput"
	fps 30
}
