// Created by Crowbar 0.68

// Stored modelname (without quotes): "C:\Program Files\ICQ\Received Files\Maverick\telegraph_key50.mdl"
$modelname "telegraph_key.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "telegraph_key_ref"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "joint1" -7.55 -0.46 -8.84 7.6 5.18 16.290001

$sequence "idle" {
	"telegraph_key_anims\idle"
	fps 10
}
