// Created by Crowbar 0.68

// Stored modelname (without quotes): "C:\WIN\DESKTOP\w_suit.mdl"
$modelname "w_suit.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "wrld_suit"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Player_Mesh" -18.860001 -18.439999 -18.07 18.24 3.459999 18.200001

$sequence "idle" {
	"w_suit_anims\idle"
	fps 30
}
