// Created by Crowbar 0.68

// Stored modelname (without quotes): "C:\MilkShape 3D\Wanted\Coat\w_battery.mdl"
$modelname "w_battery.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "wcoat"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bone01" -5.15 -5.15 -9.2 5.15 5.15 9.2

$sequence "idle" {
	"w_battery_anims\idle"
	fps 30
}
