// Created by Crowbar 0.68

// Stored modelname (without quotes): "F:\SIERRA\Half-Life\wantedhl\models\Snakegibs\snakegibs.mdl"
$modelname "snakegibs.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "parts"
{
	studio "snake_jawbone"
	studio "snake_tail"
	studio "snake_meat"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "joint1" -1.29 -1.2 -1.63 0.79 0.66 1.89

$sequence "horse_idle" {
	"snakegibs_anims\horse_idle"
	fps 30
}
