// Created by Crowbar 0.68

// Stored modelname (without quotes): "F:\knife2\w\w_knife.mdl"
$modelname "w_knife.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "crowbar"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Box01" -2.58 -1.36 -4.29 7.55 1.36 39.07

$sequence "idle" {
	"w_knife_anims\idle"
	fps 30
}
