// Created by Crowbar 0.68

// Stored modelname (without quotes): "C:\WINDOWS\Desktop\Mods\w_gattlinggun70.mdl"
$modelname "w_gattlinggun.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "gatling"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Box01" -2.58 -1.36 -4.29 7.55 1.36 39.07

$sequence "idle" {
	"w_gattlinggun_anims\idle"
	fps 30
}
