// Created by Crowbar 0.68

// Stored modelname (without quotes): "valve/models/big_rock.mdl"
$modelname "big_rock.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "large_rock_reference"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "GeoSphere01" -15.66 -16.530001 -16.93 15.66 16.530001 16.360001

$sequence "idle1" {
	"big_rock_anims\idle1"
	fps 30
}
