// Created by Crowbar 0.68

// Stored modelname (without quotes): "F:\sierra\half-half\wantedhl\Models\Flag2\flag2.mdl"
$modelname "flag2.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "Flag_Biped1"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bone01" -15.39 -2.61 -2.15 15.52 62.689999 1.57

$sequence "wave_idle" {
	"flag2_anims\wave_idle"
	ACT_IDLE 1
	fps 10
	loop
}
