// Created by Crowbar 0.68

// Stored modelname (without quotes): "D:\Wanted\Models\Non Animated\Pickaxe\pickaxe.mdl"
$modelname "pickaxe.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "pickaxe"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "temp2" -21.24 -10.16 0 0 14.54 43.139999

$sequence "idle" {
	"pickaxe_anims\idle"
	fps 30
}
