// Created by Crowbar 0.68

// Stored modelname (without quotes): "F:\bow\ammo\models\w_bowammo.mdl"
$modelname "w_bowammo.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "clip"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Box01" -3.08 -1.27 -3.93 2.76 1.27 12.83

$sequence "idle" {
	"w_bowammo_anims\idle"
	fps 30
}
