// Created by Crowbar 0.68

// Stored modelname (without quotes): "F:\wanted\dual_colts\w\w_colts.mdl"
$modelname "w_colts.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "w_colts_ref"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Line02" -9.06 -8.83 -13.53 4.1 0 14.47

$sequence "idle" {
	"w_colts_anims\idle"
	fps 30
}
