// Created by Crowbar 0.68

// Stored modelname (without quotes): "F:\wanted\buff\w\w_buffalogun.mdl"
$modelname "w_buffalogun.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "wrld_shotgun"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Box01" -20.41 -6.68 -2.62 20.41 6.68 2.62

$sequence "idle" {
	"w_buffalogun_anims\idle"
	fps 30
}
