// Created by Crowbar 0.68

// Stored modelname (without quotes): "D:\Wanted\Models\Non Animated\Medkit\w_medkit.mdl"
$modelname "w_medkit.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "w_medkit"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Box01" -23.16 -13.66 -0.05 11.47 12.78 6.72

$sequence "idle" {
	"w_medkit_anims\idle"
	fps 30
}
