// Created by Crowbar 0.68

// Stored modelname (without quotes): "D:\sierra\Half-life\valve\models\w_357.mdl"
$modelname "w_pistol.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "w_colt"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Cylinder01" -16.860001 -7.29 -2.25 10.27 2.99 0.72

$sequence "idle" {
	"w_pistol_anims\idle"
	fps 30
}
