// Created by Crowbar 0.68

// Stored modelname (without quotes): "F:\Wanted in Progress\Models\Pistol\w_pistolammobox.mdl"
$modelname "w_pistolammobox.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "w_pythonammobox"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Box02" -6.08 -2.69 -2.11 5.53 2.69 5.62

$sequence "idle" {
	"w_pistolammobox_anims\idle"
	fps 30
}
