// Created by Crowbar 0.68

// Stored modelname (without quotes): "E:\Wanted\Models\Tombstone\Current tombstone 10-5\tombstone.mdl"
$modelname "tombstone.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "tombstone"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "joint1" -11.57 -4.97 -6.34 5.27 23.65 7.3

$sequence "rise" {
	"tombstone_anims\rise"
	fps 30
}
