// Created by Crowbar 0.68

// Stored modelname (without quotes): "C:\MilkShape 3D\Wanted\telegram.mdl"
$modelname "telegram.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "envelope1"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Rectangle01" -7.19 -10.8 0 7.2 10.8 1.07

$sequence "idle1" {
	"telegram_anims\idle1"
	fps 30
}
