// Created by Crowbar 0.68

// Stored modelname (without quotes): "C:\Program Files\ICQ\Received Files\Tone\glass.mdl"
$modelname "glass.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "glass"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "skin" -3.05 -2.78 0 3.06 3.33 7.16

$sequence "idle" {
	"glass_anims\idle"
	fps 30
}
