// Created by Crowbar 0.68

// Stored modelname (without quotes): "F:\Wanted in Progress\Models\Cactus\cactus.mdl"
$modelname "cactus.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "cactus1"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "skin" -19.26 -24.68 0 7.92 31.91 167.75

$sequence "idle" {
	"cactus_anims\idle"
	fps 30
}
