// Created by Crowbar 0.68

// Stored modelname (without quotes): "C:\MilkShape 3D\Wanted\Ribs\steer_ribs.mdl"
$modelname "steerribs.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "body"
{
	studio "steer_ribs"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "joint1" -17.58 -11.87 -64.870003 4.94 1.75 0

$sequence "idle1" {
	"steerribs_anims\idle1"
	fps 30
}
