// Created by Crowbar 0.68

// Stored modelname (without quotes): "F:\bow\p\models\p_bow.mdl"
$modelname "p_bow.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "reference_crowbar"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bip01 Neck" -2.869898 0 -4.140396 0 1.399663 0
$hbox 0 "Box01" -1.55 -0.81 -2.57 4.53 0.83 23.450001

$sequence "idle" {
	"p_bow_anims\idle"
	fps 30
}
