// Created by Crowbar 0.68

// Stored modelname (without quotes): "D:\Wanted\Models\Bottle\bottle.mdl"
$modelname "bottle.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "bottle"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "skin" -3.51 -3.51 0 3.51 3.51 19.09

$sequence "idle" {
	"bottle_anims\idle"
	fps 30
}
