// Created by Crowbar 0.68

// Stored modelname (without quotes): "C:\WINDOWS\Desktop\Mods\Models\w_coltsbox400.mdl"
$modelname "w_coltsbox.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "body"
{
	studio "colts_ammo"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "joint1" -8 -5 -8 8 11 8

$sequence "idle1" {
	"w_coltsbox_anims\idle1"
	fps 30
}
