// Created by Crowbar 0.68

// Stored modelname (without quotes): "D:\Wanted\Models\Dish\dish.mdl"
$modelname "dish.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "dish"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "skin" -8.42 -8.42 0 8.42 8.42 2.18

$sequence "idle" {
	"dish_anims\idle"
	fps 30
}
