// Created by Crowbar 0.68

// Stored modelname (without quotes): "F:\Wanted in Progress\Models\Gattling Gun\w_gatammo.mdl"
$modelname "w_gattlinggun_belt.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "gatammo"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Box02" -2.75 -6.04 0 2.03 6.72 2.04

$sequence "idle" {
	"w_gattlinggun_belt_anims\idle"
	fps 30
}
