// Created by Crowbar 0.68

// Stored modelname (without quotes): "D:\Wanted\Models\Non Animated\Wheelside\wagonwheel.mdl"
$modelname "wheelside.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "wheel"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "skin" 0 -9.31 -1.39 84.120003 0.46 81.809998

$sequence "idle" {
	"wheelside_anims\idle"
	fps 30
}
