// Created by Crowbar 0.68

// Stored modelname (without quotes): "F:\wanted\beartrap_ammo\w_beartrapammo.mdl"
$modelname "w_beartrapammo.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "ref"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "joint1" -8.46 -0.06 -22.58 15.93 17.99 11.26

$sequence "idle" {
	"w_beartrapammo_anims\idle"
	fps 30
}
