// Created by Crowbar 0.68

// Stored modelname (without quotes): "D:\Wanted\Models\Non Animated\Shovel\shovel.mdl"
$modelname "shovel.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "shovel"
}

$flags 0

$externaltextures


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "temp2" -21.040001 -7.35 0 0 6.2 46.720001

$sequence "idle" {
	"shovel_anims\idle"
	fps 30
}
