// Created by Crowbar 0.68

// Stored modelname (without quotes): "F:\wanted\gat2\p\p_gattlinggun.mdl"
$modelname "p_gattlinggun.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "reference_gatling"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Bip01 Neck" -2.869898 0 -4.140396 0 1.399663 0
$hbox 0 "02" -3.85 -3.99 -9.51 4.36 4.58 19.389999

$sequence "idle" {
	"p_gattlinggun_anims\idle"
	fps 30
}
