// Created by Crowbar 0.68

// Stored modelname (without quotes): "C:\WINDOWS\Desktop\mavfixshit\shotgun\w_shotgun.mdl"
$modelname "w_shotgun.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "w_shotgun_ref"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "joint1" -3.09 -1.36 -22.66 2.7 2.18 27.870001

$sequence "idle" {
	"w_shotgun_anims\idle"
	fps 10
}
